[tool.pysen]
version = "0.11"

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = true
mypy_preset = "strict"
line_length = 88
py_version = "py311"
[[tool.pysen.lint.mypy_targets]]
  paths = ["."]


[tool.poetry]
name = "aoirint-mcping-server"
version = "0.0.0"
description = ""
authors = ["aoirint <aoirint@gmail.com>"]
readme = "README.md"
packages = [{include = "aoirint_mcping_server"}]

[tool.poetry.dependencies]
python = "~3.11"
pydantic = "^2.7.1"
sqlalchemy = "^2.0.30"
psycopg2-binary = "^2.9.9"

[tool.poetry.group.web-api.dependencies]
fastapi = "^0.111.0"
uvicorn = {extras = ["standard"], version = "^0.30.0"}

[tool.poetry.group.bedrock-updater.dependencies]
schedule = "^1.2.2"
mcstatus = "^11.1.1"

[tool.poetry.group.java-updater.dependencies]
schedule = "^1.2.2"
mcstatus = "^11.1.1"

[tool.poetry.group.dev.dependencies]
mypy = "^1.10.0"
pysen = "^0.11.0"
flake8 = "^7.0.0"
flake8-bugbear = "^24.4.26"
black = "^24.4.2"
isort = "^5.13.2"
pyinstaller = "^6.7.0"
wheel = "^0.43.0"
types-pyyaml = "^6.0.12.20240311"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
