[tool.pysen]
version = "0.10"

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = true
mypy_preset = "strict"
line_length = 88
py_version = "py311"
[[tool.pysen.lint.mypy_targets]]
  paths = ["."]


[tool.poetry]
name = "aoirint-mcping-server"
version = "0.1.0"
description = ""
authors = ["aoirint <aoirint@gmail.com>"]
readme = "README.md"
packages = [{include = "aoirint_mcping_server"}]

[tool.poetry.dependencies]
python = "~3.11"
pydantic = "^2.3.0"
types-pyyaml = "^6.0.12.6"
sqlalchemy = "^2.0.4"
psycopg2-binary = "^2.9.5"

[tool.poetry.group.web-api.dependencies]
fastapi = "^0.109.1"
uvicorn = {extras = ["standard"], version = "^0.20.0"}

[tool.poetry.group.bedrock-updater.dependencies]
schedule = "^1.1.0"
mcstatus = "^10.0.1"

[tool.poetry.group.java-updater.dependencies]
schedule = "^1.1.0"
mcstatus = "^10.0.1"

[tool.poetry.group.dev.dependencies]
mypy = "^1.0"
pysen = "^0.10.5,>=0.10.5"
flake8 = "^6.0.0"
flake8-bugbear = "^23.2.13"
black = "^23.1.0"
isort = "^5.12.0"
pyinstaller = "^5.8.0"
wheel = "^0.38.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
